spring.application.name=DoAn_QuanLyTinhNguyen_Nhom3

# ====================== DATASOURCE ======================
spring.datasource.url=jdbc:mysql://localhost:3306/quan_ly_tinh_nguyen
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ====================== JPA / HIBERNATE ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# ====================== JWT ======================
app.jwt.secret=nhom3QuanLyTinhNguyenSecretKeyMin32CharsLong!
app.jwt.expiration-ms=86400000

# ====================== SWAGGER ======================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
